version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - .docker/data/mongodb/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped